### PR TITLE
Clean yarn.lock

### PR DESCRIPTION
**Pull request by pvinis**
# Summary
I removed `yarn.lock` and run `yarn install`, and this is what came out. Should we merge? 🤔 

## Checklist

- [ ] I tested this thoroughly
- [ ] I added the documentation in `README.md` (if needed)

### CODE REVIEW

**Comment by lucasbento** [comment]
@pvinis: can you check the deploy preview to see if everything is working?

**Comment by pvinis** [comment]
Seems to be alright.

**Comment by pvinis** [comment]
@lucasbento Could you checkout this PR, and remove the lockfile, then yarn install and check the diff? I'm curious if your computer will generate the same lock file or not.

For reference, I have `node 13.9.0` and `yarn 1.22.0`.

**Comment by lucasbento** [comment]
@pvinis: I'll check that!

**Comment by lucasbento** [comment]
@pvinis: nope, got a different lockfile with `yarnpkg.com` instead of `npmjs.org`.
I suggest not merging this.

**Comment by pvinis** [comment]
Hmmmm good to know. Strange. Let's close this then and I'll investigate why this happens.

**Pull request closed without merging**
