### PR TITLE
feat(DiffComment): allow for comment collapse

### PR DESCRIPTION
**Pull request by vinnyA3**
# Summary

This PR resolves [#39](https://github.com/react-native-community/upgrade-helper/issues/39); The feature allows for one to collapse comments--enabling better copy/pasting of code.  To implement, I used a checkbox & *css*'s sibling combinator to display / hide the comment box.

**note**: I put the checkbox inline with the comment; however, an *antd* checkbox can be put in the title bar for each diff w/ comments (allowing for a toggling of all comments like @kelset suggested in the issue)

**note2**:  You can avoid toggling the comments all together by using the `user-select` css property.  [https://caniuse.com/#search=user-select](https://caniuse.com/#search=user-select)

## Test Plan

1. Clone & run locally
2. Visit `http://localhost:3000/`
3. Choose versions (to & from)
4. Navigate to comment(s) and toggle on/off

## Checklist

- [x] I tested this thoroughly
- [x] I added the documentation in `README.md` (if needed)

comment-collapse

Screen Shot 2019-07-18 at 10 53 01 PM

Screen Shot 2019-07-18 at 10 53 55 PM

### CODE REVIEW

**Comment by lucasbento** [comment]
@vinnyA3: this is so damn cool, thank you so much for working on this.

I have just one suggestion: what do you think about changing the checkbox to be a button instead or perhaps the checkbox from ant.design? would love to hear your opinion on this!

**Comment by vinnyA3** [comment]
@lucasbento I'm glad that I could help out !

I think a button would be a nice choice, and the design would remain consistent as `ant design` would be used.  Gitlab does this pretty nicely--where you can toggle discussions.

*ie*:
Screen Shot 2019-07-19 at 7 16 53 PM

Using a button + icon here would be cool.  If you don't mind some refactoring to use state within the `DiffComment` component, I'd say a button would be the best option.
The toggle flow would be as follows:
  * The button is clicked -> state is updated (`displayComment`) -> the comment is then displayed

Let me know what you think!

**Comment by lucasbento** [comment]
@vinnyA3: that sounds like a cool approach, that little piece of UI is pretty cool as well 😁

**Comment by vinnyA3** [comment]
@lucasbento Made the change!

`displayComment`:

Screen Shot 2019-07-22 at 3 03 36 PM

`!displayComment`:

Screen Shot 2019-07-22 at 3 05 00 PM

---

Let me know if that's okay 👨‍💻

**Comment by lucasbento** [comment]
It's live: https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.4 🤗

**Comment by vinnyA3** [comment]
Awesome ! 🚀 😄

**Pull request merged**
