### PR TITLE
Fix UI styles

### PR DESCRIPTION
**Pull request by lucasbento**
# Summary

This PR puts back the logo that we used for loading and add a little bit of margin below the title.

## Checklist

- [x] I tested this thoroughly
- [x] I added the documentation in `README.md` (if needed)

### CODE REVIEW

**Comment by lucasbento** [comment]
cc @RubenSandwich
I just put the _old logo_ back for the spinner as the current one is kinda squared and doesn't really work well for the loading, please let me know your thoughts.

I'll merge this right now but we can definitely discuss further.

**Comment by RubenSandwich** [comment]
@lucasbento No worries, that makes sense.

Another idea for the loading animation is to use a [skeleton screen](https://css-tricks.com/building-skeleton-screens-css-custom-properties/).

**Comment by lucasbento** [comment]
@RubenSandwich: that would be so cool, the spinner is there just because we did it in a rush.

Would you have time to open a PR implementing it?

**Comment by RubenSandwich** [comment]
@lucasbento Yeah give me about a week and I'll have a PR.

**Comment by lucasbento** [comment]
@RubenSandwich: awesome! created an issue for it: #58.

Thank you for your work 🙂

**Comment by RubenSandwich** [comment]
@lucasbento No worries, thanks for managing this project.

**Pull request merged**
