### PR TITLE
vote for upgrade-helper!

### PR DESCRIPTION
**Pull request by pvinis**
Is this too much to add? 😇

### CODE REVIEW

**Comment by lucasbento** [comment]
Can't say that I haven't thought about it, it's a good idea.

What do you think about putting this as a badge like badge?

The `alt`/`title` can be `Vote for Upgrade Helper on React Native Open Source Awards` and it can be right by the side of the `Star` button.

**Comment by pvinis** [comment]
oh yes i like that idea more. i didnt know badges supported logos 😯

**Comment by lucasbento** [comment]
Me neither, I just tried react there and it worked haha

**Comment by pvinis** [comment]
Let's win! 🥇😁

**Pull request merged**
