### PR TITLE
Click the completed files counter to go to the Done section

### PR DESCRIPTION
**Pull request by benomatis**
Click the completed files counter to go to the Done section, click again to go back to top

This is an implementation of engancement request https://github.com/react-native-community/upgrade-helper/issues/215

It's just one variant... ;)

### CODE REVIEW

**Comment by benomatis** [comment]
Sorry, I don't understand what that test error is supposed to mean and how I can fix it.

**Comment by pvinis** [comment]
I think it just needs to update the snapshot. I can do it.

**Comment by pvinis** [comment]
Done. Basically when running `yarn test` and that test fails, you can press `u` and it will update the snapshot.

**Comment by pvinis** [comment]
Hm, where did my commit go? 😆

I thought I could push on the same thing here, but apparently it went here. https://github.com/react-native-community/upgrade-helper/commit/f0992e074bc0d50ac923b47b8812b5c834fe00c5 You can just grab that change, or try to update it yourself. :D

**Comment by benomatis** [comment]
@pvinis I just merged your changes, and it looks like all tests went through (sorry, I'm not an experienced tester, not even close, apparently) ;) Thanks!

**Pull request merged**
