### PR TITLE
Show comments in the diff

### PR DESCRIPTION
**Pull request by lucasbento**
# Summary

This PR adds the ability to show comments in the diff, the comments are provided by a file under `./src/releases`. Related to #10.

## Test Plan

Run the app locally and select `0.60.0.rc-0` as the destination version.

---

image

---

image

### CODE REVIEW

**Comment by pvinis** [comment]
🤣 I looooove those comments! I don't even need to talk about the second one!

**Comment by kelset** [comment]
So the only blocker here for now is the copy for the comments?

**Comment by lucasbento** [comment]
@kelset: I'm waiting for @pvinis to approve the code so we can merge it, before merging it I'll remove the current comments, right now they are here just to illustrate how to add them.

**Comment by kelset** [comment]
Gotcha - I guess we want to have that in the readme right? Because these comments will live in this repo

**Comment by pvinis** [comment]
I guess they will live here yes. But I didn't get what you mean with put it in the readme?

**Comment by kelset** [comment]
oh sorry 😅 yeah I meant, like a section of the readme explaining how comments inline can be added

**Comment by kelset** [comment]
my only concern is, what will happen if we have let's say a jump from 57 to 59, and the comment that we want to show was something that would be in 58?

**Comment by lucasbento** [comment]
@kelset: it will show anyway unless `0.59` has a comment on the same line.

**Comment by lucasbento** [comment]
@kelset: about adding docs for comments I created #28 to keep track of it.

**Pull request merged**
