### PR TITLE
Improve comment UI

### LINKED ISSUE #226: Add some color border or highlight on the comments
# Feature Request
When quickly scanning this, the comment is almost invisible. When we look at a diff, we are looking for green and red, and white is just background noise.

Screen Shot 2020-03-30 at 15 51 57

I think we should try to add some border that would make it pop more. Maybe a light blue or something that is not used in the diffs normally.

### PR DESCRIPTION
**Pull request by lucasbento**
# Summary

This PR partly fixes #226, the rest of the fix will come in later :D

## Test Plan

1. Open the links from the comments;
1. Click them for collapsing;
1. Click them again for showing;
1. Make sure that you can select the comment when it's showing but not when it's hidden;

## Checklist

- [x] I tested this thoroughly
- [x] I added the documentation in `README.md` (if needed)

## Known issues

Unfortunately I can't get the disable of selection working on Safari, I really tried though.

---

<details>
<summary>Before</summary>

Before
</details>

<details>
<summary>After</summary>

After
</details>

<details>
<summary>Animation</summary>

animation
</details>

### CODE REVIEW

**Comment by lucasbento** [comment]
Deploy preview can be seen at: https://5e9adab38d1bfbcee743aaa0--upgrade-helper.netlify.app/

The integration did not kick in as the base branch is not `master`.

**Comment by pvinis** [comment]
Oh nice! that's awesome.

**Comment by lucasbento** [comment]
> @pvinis: Could we add like a - or something on the left part so it's more obvious it's collapsible?

Can you elaborate a little bit more on this? I'm not sure I follow

**Comment by lucasbento** [comment]
Superseded by #237.

**Pull request closed without merging**
