### PR TITLE
Replace `RnDiffApp` in the diff content

### LINKED ISSUE #227: Android package name does not update
# Bug
I changed the app name in the settings; however, the package name is still the same.

Screen Shot 2020-04-03 at 9 45 13 AM

## React Native versions
0.62

## Steps to reproduce

Describe what you expected to happen:

1. Diff from 61.1 -> 0.62

2. Change app name in settings

3. New flipper file in Android should also include the app's package name

### LINKED ISSUE #230: Project name does not updated in comments of project.pbxproj file
# Bug

I changed the app name in the settings; however, the app name in the comment of `project.pbxproj` file is still the same.

image

## React Native versions

from RN 0.59.10
to RN 0.62.2

## Steps to reproduce

Describe what you expected to happen:

1. Diff from 0.59.10 -> 0.62.2

2. Change app name in settings

3. comments in the file `project.pbxproj` should also include the app's name

### PR DESCRIPTION
**Pull request by lucasbento**
# Summary

Currently we are only replacing the `rndiffapp` name in file paths, this PR replaces the `RnDiffApp` mentions in the diff changes as well.

Fixes #227.
Fixes #230.

## Test Plan

1. Add app name in settings button;
1. Check that the path has been replaced with the name provided;
1. Make sure that the `View file` button works fine;
1. Check that the content of files like `Podfile` has the name provided.

## Checklist

- [x] I tested this thoroughly
- [x] I added the documentation in `README.md` (if needed)

### CODE REVIEW

**Comment by pvinis** [comment]
This looks great.

I remember we talk about this, when we click to view the file, the name is, of course, rndiffapp in there. I can't remember what we decided on, but I think just leaving it as it is now is fine. If we plan to leave it like that, could we maybe add an alert or a popup tooltip or something, so when the user has changed the project name, and is about to click on view/download file, to get a notice that they should make sure they replace manually `RnDiffApp` with `<name from input field>` and `rndiffapp` with `<name from input field in lowercase>`?

What are your thoughts on this, before we merge this one?

**Comment by lucasbento** [comment]
> @pvinis: get a notice that they should make sure they replace manually RnDiffApp with <name from input field> and rndiffapp with <name from input field in lowercase>?

Hmm, this makes a lot of sense.

I think we could add the small text that we have at the useful content section.

What we could do is:

1. Show an alert after clicking on `View file` with that small text.
  ✅ Alert should be shown only after clicking the button
  ✅ Alert should be shown only once, if the user clicks another `View file` it should go directly
  ❌ If the user reloads the page they will see the alert again which can be very annoying.
1. Show tooltip with small text when hovering `View file`
  ✅ Very small
  ❌ Perhaps too small, can be unnoticeable
  ❌ Maybe weird? not sure

Thoughts?

**Comment by vamshi9666** [comment]
when clicked on view file , raw file is shown in new browser window.App name is still not reflecting there. checked in deploy preview.

**Comment by lucasbento** [comment]
> @vamshi9666: when clicked on view file , raw file is shown in new browser window.App name is still not reflecting there. checked in deploy preview.

Yeah, this is something that we can't change as it leads to a file on GitHub itself.

Do you have any suggestions on what to do regarding this?

**Pull request merged**
